CREATE TABLE GEOLOCATION
(   
   ZIPCODE_PREFIX VARCHAR(255) PRIMARY KEY NOT NULL,
   LONG DECIMAL(9,6),
   LAT DECIMAL(9,6),
   CITY VARCHAR(255),
   STATE VARCHAR(255)
)
CREATE TABLE SELLER 
(
	SELLER_ID  VARCHAR(255)  PRIMARY KEY NOT NULL ,
	ZIPCODE_PREFIX VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	FOREIGN KEY (ZIPCODE_PREFIX) REFERENCES GEOLOCATION(ZIPCODE_PREFIX)

)
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT IDENTITY(1,1), 
    CUSTOMER_UNIQUE_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    ZIPCODE_PREFIX VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	FOREIGN KEY (ZIPCODE_PREFIX) REFERENCES GEOLOCATION(ZIPCODE_PREFIX) 

)
CREATE TABLE PRODUCT_ORDER
(
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT,
	ORDER_STATUS VARCHAR(255),
	ORDER_PURCHASE_TIMESTAMP DATETIME,
	ORDER_APPROVED_AT DATETIME,
	ORDER_DELIVER_CARRIER_DATE DATETIME

)

CREATE TABLE PRODUCT_CATEGORY(
    PRODUCT_CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(255)
)

CREATE TABLE PRODUCT
(
    PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PRODUCT_CATEGORY_ID INT,
	PRODUCT_NAME_LENGTH INT,
	PRODUCT_DECSRIOTION_LENGTH INT,
	PRODUCT_WEIGHT_G INT,
	PRODUCT_LENGTH_CM INT,
	PRODUCT_HEIGHT_CM INT,
	PRODUCT_WIDTH_CM INT
	FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID)
)

CREATE TABLE ORDER_PAYMENT
(
    ORDER_PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ORDER_ID INT,
	PAYMENT_TYPE VARCHAR(255),
	PAYMENT_INSTALLMENTS INT,
	PAYMENT_VALUE FLOAT,
	FOREIGN KEY (ORDER_ID) REFERENCES PRODUCT_ORDER(ORDER_ID)
)
CREATE TABLE ORDER_ITEM
(
	ORDER_ITEM_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ORDER_ITEM VARCHAR(255),
	PRODUCT_ID INT,
	SELLER_ID VARCHAR(255),
	PRICE TEXT,
	FREIGHT_VALUE TEXT,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
	FOREIGN KEY (SELLER_ID) REFERENCES SELLER(SELLER_ID)
)
CREATE TABLE ORDER_REVIEWS
(
	REVIEW_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ORDER_ID INT,
	REVIEW_SCOPE VARCHAR(255),
	REVIEW_COMMENT_TITLE VARCHAR(255),
	REVIEW_COMMENT_MSG VARCHAR(255),
	REVIEW_CREATION_DATE VARCHAR(255),
	REVIEW_ANSWER_TIME_STAMP VARCHAR(255),
	FOREIGN KEY (ORDER_ID) REFERENCES PRODUCT_ORDER(ORDER_ID)
)

------------------------------------------------------
----------- CREATING THE STAGING TABLES FOR THE DATA FILES --------------

CREATE TABLE GEOLOCATION_STAGE
(   
   
   GEOLOCATION_ZIP_CODE_PREFIX VARCHAR(255) NOT NULL,
   GEOLOCATION_LAT DECIMAL(18,15),
   GEOLOCATION_LONG DECIMAL(9,6),
   GEOLOCATION_CITY VARCHAR(255),
   GEOLOCATION_STATE VARCHAR(255),
  
)

CREATE TABLE SELLER_STAGE 
(
	SELLER_ID  VARCHAR(255) PRIMARY KEY NOT NULL ,
	SELLER_ZIPCODE_PREFIX VARCHAR(255),
	SELLER_CITY VARCHAR(255),
	SELLER_STATE VARCHAR(255),
)
CREATE TABLE CUSTOMER_STAGE(
    CUSTOMER_ID VARCHAR(255) ,
	CUSTOMER_UNIQUE_ID VARCHAR(255) NOT NULL,
    ZIPCODE_PREFIX VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
)
CREATE TABLE PRODUCT_ORDER_STAGE
(
    ORDER_ID VARCHAR(255) PRIMARY KEY NOT NULL,
	CUSTOMER_ID VARCHAR(255),
	ORDER_STATUS VARCHAR(255),
	ORDER_PURCHASE_TIMESTAMP TEXT,
	ORDER_APPROVED_AT TEXT,
	ORDER_DELIVER_CARRIER_DATE TEXT

)

CREATE TABLE PRODUCT_CATEGORY_STAGE(
    PRODUCT_CATEGORY_NAME VARCHAR(255),
	PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(255)
)
CREATE TABLE PRODUCT_STAGE
(
    PRODUCT_ID VARCHAR(255) PRIMARY KEY NOT NULL,
	PRODUCT_NAME_LENGTH TEXT,
	PRODUCT_DECSRIOTION_LENGTH INT,
	PRODUCT_WEIGHT_G INT,
	PRODUCT_LENGTH_CM INT,
	PRODUCT_HEIGHT_CM INT,
	PRODUCT_WIDTH_CM TEXT
	
)

CREATE TABLE ORDER_PAYMENT_STAGE
(
    
	ORDER_ID VARCHAR(255),
	PAYMENT_TYPE VARCHAR(255),
	PAYMENT_INSTALLMENTS INT,
	PAYMENT_VALUE FLOAT,
	
)
CREATE TABLE ORDER_ITEM_STAGE
(
	ORDER_ITEM_ID VARCHAR(255) NOT NULL,
	ORDER_ITEM VARCHAR(255),
	PRODUCT_ID VARCHAR(255),
	SELLER_ID VARCHAR(255),
	PRICE TEXT,
	FREIGHT_VALUE TEXT
	
)
CREATE TABLE ORDER_REVIEWS_STAGE
(
	REVIEW_ID VARCHAR(255) NOT NULL,
	ORDER_ID VARCHAR(255),
	REVIEW_SCOPE VARCHAR(255),
	REVIEW_COMMENT_TITLE VARCHAR(255),
	REVIEW_COMMENT_MSG VARCHAR(255),
	REVIEW_CREATION_DATE TEXT,
	REVIEW_ANSWER_TIME_STAMP TEXT,
	
)




