CREATE TABLE GEOLOCATION
(   
   ZIPCODE_PREFIX VARCHAR(255) PRIMARY KEY NOT NULL,
   LONG DECIMAL(9,6),
   LAT DECIMAL(9,6),
   CITY VARCHAR(255),
   STATE VARCHAR(255)
)
CREATE TABLE SELLER 
(
	SELLER_ID  INT iDENTITY(1,1) PRIMARY KEY NOT NULL ,
	ZIPCODE_PREFIX VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	FOREIGN KEY (ZIPCODE_PREFIX) REFERENCES GEOLOCATION(ZIPCODE_PREFIX)

)
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ZIPCODE_PREFIX VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	FOREIGN KEY (ZIPCODE_PREFIX) REFERENCES GEOLOCATION(ZIPCODE_PREFIX) 

)
CREATE TABLE PRODUCT_ORDER
(
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT,
	ORDER_STATUS VARCHAR(255),
	ORDER_PURCHASE_TIMESTAMP DATETIME,
	ORDER_APPROVED_AT DATETIME,
	ORDER_DELIVER_CARRIER_DATE DATETIME
	FOREIGN KEY CUSTOMER_ID REFERENCES CUSTOMER(CUSTOMER_ID)

)








    
   

